<template>
  <button
    @click="click"
    class="header-login__btn button"
    :class="{
      'button--text': text,
      'button--loading': loading
    }"
  >
    <span class="button__text">
      <slot />
    </span>
    <div class="button__spinner">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        width="39px"
        height="39px"
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid"
        style="background-color:transparent;"
      >
        <circle
          cx="50"
          cy="50"
          fill="none"
          stroke="#e15b64"
          stroke-width="10"
          r="35"
          stroke-dasharray="164.93361431346415 56.97787143782138"
          transform="matrix(1,0,0,1,0,0)"
          style="transform:matrix(1, 0, 0, 1, 0, 0);animation-play-state:paused"
        ></circle>
        <!-- generated by https://loading.io/ -->
      </svg>
    </div>
  </button>
</template>
<script>
export default {
  name: 'Button',
  props: {
    text: {
      type: Boolean,
      default: false
    },
    loading: {
      type: Boolean,
      default: false
    }
  },
  methods: {
    click () {
      if (this.loading) return
      this.$emit('click')
    }
  }
}
</script>
<style lang="sass">
.button
  user-select: none
  -webkit-tap-highlight-color: transparent
  position: relative
  border: none
  border-radius: 4px
  cursor: pointer
  outline: none
  padding: 10px 32px
  font-family: Rubik, default sans-serif
  font-weight: 500
  font-size: 16px
  &__spinner
    position: absolute
    display: none
    top: 0
    right: 0
    bottom: 0
    left: 0
    svg
      margin: 0
      animation: 1s linear 0s rotation infinite
      circle
        stroke: #fff
  &--loading
    pointer-events: none
    .button__spinner
      display: block
    .button__text
      visibility: hidden
  &--text
    border: none
    background: none
  &--accent
    background-color: $color-accent
    color: #fff
  &--accent:active
    background-color: lighten($color-accent, 20%)
  &--accent-flat:active
    color: lighten($color-accent, 20%)
  &--accent-flat
    color: $color-accent
    .button__spinner
      svg
        circle
          stroke: $color-accent

@keyframes rotation
  from
    transform: rotate(0deg)
  to
    transform: rotate(360deg)

@media (hover: hover)
  .button
    &--accent:hover
      background-color: lighten($color-accent, 20%)
    &--accent-flat:hover,
    &--accent-flat:active
      color: lighten($color-accent, 20%)
</style>
